title: Ishan Srivastava # your name (or website title) here

logo: "/images/logo.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)

  <p align="center">
  <a href="pdf/cv_ishan.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ishansrivastava96/">LinkedIn</a> |
  <a href="https://github.com/Ishan-phys">GitHub</a>
  </p>
  
  I am a Data Scientist with a foundation in Theoretical Physics, 
  presently working at Intellithink Industrial IoT Labs. 
  My enthusiasm for continual learning drives me to actively share my knowledge in the most public and accessible manner possible 
  <br><br>  
  I specialize in leveraging Machine Learning and Deep Learning techniques for Predictive Maintenance and 
  Anomaly Detection in the realm of Industrial Heavy Machinery and Equipment. 
  Through the application of ML/DL, my efforts contribute to significant cost savings, mitigating unplanned downtime and optimizing maintenance expenditures, resulting in multimillion-dollar benefits for organizations.
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
